apiVersion: v1
kind: Pod
metadata:
  name: jigs-test-pod
  labels:
    name: jigs-test-pod
    app: nodejs-app
spec:
  containers:
    - name: jigs-test-pod
      image: jigs221/nodejs-githubactions-k8s
      ports:
        - containerPort: 5000
