apiVersion: v1
kind: Service
metadata:
  name: jigs-test-pod
  labels:
    name: jigs-test-pod
    app: nodejs-app
spec:
  type: LoadBalancer
  ports:
    - port: 5000
      targetPort: 5000
  selector:
    name: jigs-test-pod
    app: nodejs-app
