apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jigs-ingress
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: jigs-test-pod
                port:
                  number: 5000
