apiVersion: v1
kind: Service
metadata:
  name: jigs-ingress
  labels:
    name: jigs-test-pod
    app: nodejs-app
spec:
  ports:
  - name: http
    port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    name: jigs-test-pod
    app: nodejs-app
  type: LoadBalancer

